import '../styles/globals.css'
import Link from 'next/link'
import { cookies } from 'next/headers'
import { prisma } from '../lib/prisma'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const uid = cookies().get('uid')?.value
  const user = uid ? await prisma.user.findUnique({ where: { id: uid }, include: { role: true } }) : null
  const loggedIn = Boolean(user)
  return (
    <html lang="en">
      <body>
        <header className="border-b bg-white">
          <div className="mx-auto flex h-12 max-w-7xl items-center justify-between px-4 text-sm">
            <nav className="flex items-center gap-5">
              <Link href="/#ponudba" className="font-medium hover:text-gray-900">Ponudba</Link>
              {loggedIn && (
                <>
                  <Link href="/urnik-tedenski" className="font-medium hover:text-gray-900">Urnik</Link>
                  <Link href="/beljakovinski-urnik" className="font-medium hover:text-gray-900">Beljakovinski urnik</Link>
                  <Link href="/moj-profil" className="font-medium hover:text-gray-900">Moj profil</Link>
                </>
              )}
            </nav>
            <div className="flex items-center gap-3">
              {loggedIn ? (
                <a href="/api/logout" className="rounded-xl bg-gray-900 px-3 py-1.5 text-xs font-semibold text-white hover:bg-black">Odjava</a>
              ) : (
                <>
                  <Link href="/prijava" className="rounded-xl border px-3 py-1.5 text-xs font-medium hover:bg-gray-50">Prijava</Link>
                  <Link href="/registracija" className="rounded-xl bg-gray-900 px-3 py-1.5 text-xs font-semibold text-white hover:bg-black">Registracija</Link>
                </>
              )}
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
